Change to haversine formula in edge.py
simulate-digital-rail/planpro-exporter pull request #2
Opened 2022-07-30 08:58 UTC by eagle3000

Wir haben die Formel in edge.py zur Nutzung der Haversine-Formel angepasst.

2022-07-30 09:02 UTC, eagle3000 commented
Wir haben auch in node.py in Zeile 90 den Pythagoras gesehen, sind uns da aber nicht sicher, ob dieser auch durch die Haversine-Formel ersetzt werden sollte. Bei Bedarf gerne noch anpassen.

In edge.py ist der Output in Metern.

2022-08-23 11:31 UTC, arneboockmeyer commented
@eagle3000 Der sollte in der `node.py` auch angepasst werden. Wir sollten hier aber dringend nochmal über die Koordinaten sprechen. PlanPro möchte die Koordinaten am Ende im DBRef Format haben. Leider liegen mir hierzu bisher kaum Dokumentationen zu, habt ihr da vielleicht etwas? Wir müssten dann ja noch von euren Koordinaten in DBRef umrechnen.

Ich würde diesen PR um ein generelles Konzept von "Settings" ergänzen. In diesen Einstellungen, die man der `generate` Methode übergeben kann, kann man dann festlegen, ob die Eingabe einfache Zahlen x und y sind, Geo-Koordinaten oder DBRef. In diesen Settings könnte man dann auch den Autor übergeben, weil aktuell immer mein Name in der PlanPro-Datei steht. Was meint ihr?

2022-08-23 11:32 UTC, arneboockmeyer requested changes
Changes requested in https://github.com/arneboockmeyer/planpro-generator/pull/2#issuecomment-1223937546

2022-08-28 14:28 UTC, rohansaw commented
Settings hören sich definitiv sinnvoll an :)

Zum DBRef format habe ich mal kurz nachgelesne und wenn ich das richtig verstehe sind DBRef koordinaten im Gauß-Krüger format auf basis eines Bessel-Ellipsoiden dargestellt [source](https://www.geopp.de/pdf/tfh_bochum11_f.pdf). Aus OSM kriegen wir die Koordinaten in WGS84. [Diese](https://docs.obspy.org/tutorial/code_snippets/coordinate_conversions.html) library bietet die möglichkeit in verschiedene Koordinaten darstellungen unter angabe der ellipsoide zu transformieren. Das werden wir uns jetzt nochmal genauer anschauen.

2022-11-15 15:21 UTC, closed without merging

2022-11-15 15:23 UTC, arneboockmeyer commented
@eagle3000 Could you please change the target branch of this PR to `main`? See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request for details.