Merge final result from DRSS 2022
simulate-digital-rail/planpro-exporter pull request #7
Opened 2022-11-15 15:44 UTC by rohansaw

- fix sizing problem by using haversine formula and decimals
- added custom project setings for generation
- allow to add actual side distance of signals instead of a hard-coded number
- further minor adaptions to be compatible with geo_nodes
- further minor changes

2022-11-17 12:24 UTC, arneboockmeyer commented
@rohansaw Could you please merge the main branch into your branch to solve the conflicts?

2022-11-17 13:41 UTC, rohansaw commented
> @rohansaw Could you please merge the main branch into your branch to solve the conflicts?

I merged it on my fork, however, I did not manage to test it yet and will not be able to do so the next days. So before a merge this should please be tested by someone.

2022-12-01 13:58 UTC, arneboockmeyer requested changes
We could think about moving all the coords stuff (representation, helper methods) to the new railway model. We should also move the config there.

2022-12-01 13:58 UTC, arneboockmeyer commented on generatorcli.py
> +            author_name="Arne Boockmeier",
This should be either set by some command or should be asked during the CLI process. In the end, its either `Boockmeyer` or some `Default Name`

2022-12-01 13:58 UTC, arneboockmeyer commented on planprogenerator/model/edge.py
> +        pi_over_180  = Decimal(math.pi/180)
There needs to be a switch here

2022-12-01 13:58 UTC, arneboockmeyer commented on planprogenerator/model/node.py
> +                pi_over_180  = Decimal(math.pi/180)
There need to be a switch here aswell

2022-12-01 13:58 UTC, arneboockmeyer commented on planprogenerator/utils/__init__.py
> +from .config import Config
Line at end of file

2022-12-01 13:58 UTC, arneboockmeyer commented on planprogenerator/utils/helpers.py
> +def dbref_coords(x, y, coord_representation: Literal['wgs84', 'dbref']):
Is this method converting the coordinates to DB Ref?

2022-12-06 23:00 UTC, jeriox commented
replaced by #10

2022-12-06 23:00 UTC, closed without merging